# Generated by Django 5.1 on 2024-08-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gioitinh',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vaitro',
            new_name='role',
        ),
    ]
